using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Linq;

namespace Polytoria.SourceGen;

[Generator]
public sealed class AssetRegistrationGenerator : IIncrementalGenerator
{
	private const string BaseAssetFullName = "Polytoria.Datamodel.Resources.BaseAsset";
    private const string InstantiableAttributeName = "Polytoria.Attributes.InstantiableAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (s, _) => s is ClassDeclarationSyntax classDecl && classDecl.BaseList != null,
				transform: static (ctx, _) => GetAssetTypeInfo(ctx))
			.Where(static m => m != null)
			.Select(static (m, _) => m!)
			.Collect();

		context.RegisterSourceOutput(classDeclarations, static (spc, classes) =>
		{
			var source = GenerateRegistrationSource(classes);
			spc.AddSource("AssetRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
		});
	}

	private static string? GetAssetTypeInfo(GeneratorSyntaxContext context)
	{
		var classDeclaration = (ClassDeclarationSyntax)context.Node;
		if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
			return null;

		if (symbol.IsAbstract)
			return null;

		if (!InheritsFrom(symbol, BaseAssetFullName))
			return null;

        // Ensure it has Instantiable attribute
        if (!HasAttribute(symbol, InstantiableAttributeName))
            return null;

		return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
	}

	private static bool InheritsFrom(INamedTypeSymbol symbol, string baseClassName)
	{
		var baseType = symbol.BaseType;
		while (baseType != null)
		{
			if (baseType.ToDisplayString() == baseClassName)
				return true;
			baseType = baseType.BaseType;
		}
		return false;
	}

    private static bool HasAttribute(INamedTypeSymbol symbol, string attributeFullName)
    {
        return symbol.GetAttributes().Any(attr => attr.AttributeClass?.ToDisplayString() == attributeFullName);
    }

	private static string GenerateRegistrationSource(ImmutableArray<string> classes)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		sb.AppendLine();
		sb.AppendLine("namespace Polytoria.Shared;");
		sb.AppendLine();
		sb.AppendLine("internal static class AssetRegistrationMap");
		sb.AppendLine("{");
		sb.AppendLine("\tpublic static void RegisterAll()");
		sb.AppendLine("\t{");

		foreach (var className in classes.OrderBy(c => c))
		{
            sb.AppendLine($"\t\t{className}.RegisterAsset();");
		}

		sb.AppendLine("\t}");
		sb.AppendLine("}");
		return sb.ToString();
	}
}
